theme = "gruvbox"

[editor]
line-number = "relative"
scroll-lines = 1
scrolloff = 7
bufferline = "always"

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
"+" = "expand_selection"
"minus" = "shrink_selection"

"[" = { "b" = "goto_previous_buffer" }
"]" = { "b" = "goto_next_buffer" }

"K" = "hover"
"A-k" = "keep_selections"

[keys.normal.space]
"q" = ":buffer-close"
"f" = "file_picker_in_current_directory"
"F" = "file_picker"

[keys.normal."0"]
c = { "r" = ":config-reload", "o" = ":config-open" }
"0" = ["collapse_selection", "keep_primary_selection"]

[keys.normal."0".i]
d = ["normal_mode", ":insert-output date +'%Y-%m-%d %R' | tr '\n' '\\0' ", "collapse_selection", "insert_at_line_end" ]
